version: "3.7"
services:
  traefik:
    image: traefik:v2.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./.htpasswd:/.htpasswd
    ports:
      - "80:80"
      - "443:443"
  ghost:
    image: ghost:3-alpine
    volumes:
      - ghost_data:/var/lib/ghost/content
    environment:
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__auth__user: ${MAILGUN_USER}
      mail__options__auth__pass: ${MAILGUN_PASS}
  frontend:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    depends_on:
      - ghost
  commento:
    image: registry.gitlab.com/commento/commento:v1.8.0
    environment:
      COMMENTO_PORT: 8060
      COMMENTO_POSTGRES: postgres://postgres:postgres@commento_db:5432/commento?sslmode=disable
      COMMENTO_CONFIG_FILE: /etc/commento.env
    depends_on:
      - commento_db
    volumes:
      - ./commento.env:/etc/commento.env
  commento_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - commento_db_data_volume:/var/lib/postgresql/data

volumes:
  ghost_data:
  commento_db_data_volume:
